machine:
  services:
    - docker

compile:
  override:
    - docker build -t texlive texlive
    - docker build -t python2 python2
    - docker build -t python3 python3

deployment:
  hub:
    branch: master
    commands:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      - docker tag texlive kieluniphysik/texlive;
      - docker push kieluniphysik/texlive;
      - docker tag python2 kieluniphysik/python2;
      - docker push kieluniphysik/$NAME;
      - docker tag python3 kieluniphysik/python3;
      - docker push kieluniphysik/python3;