sudo: required
  
matrix:
  include:
  - env: NAME=texlive
  - env: NAME=python2
  
services:
  - docker
  
script:
  - docker build -t $NAME $NAME

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag $NAME kieluniphysik/$NAME;
    docker push kieluniphysik/$NAME;
    fi