sudo: required

services:
  - docker

env:
  - NAME=texlive
  - NAME=python2

script:
  - docker build -t $NAME $NAME

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag $NAME kieluniphysik/$NAME;
    docker push kieluniphysik/$NAME;
    fi