sudo: required

services:
  - docker
  
script:
  - docker build -t texlive texlive

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag texlive kieluniphysik/texlive
    docker push kieluniphysik/texlive;
    fi