defaults: &defaults
  docker:
    - image: docker

version: 2
jobs:
  build-texlive:
    <<: *defaults
    steps:
    - checkout
    - setup_remote_docker
    - run: echo y | docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - run: docker build -t texlive texlive
    - run: docker tag texlive kieluniphysik/texlive
    - run: docker tag texlive kieluniphysik/texlive:2018
    - run: docker push kieluniphysik/texlive
  build-python2:
    <<: *defaults
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: echo y | docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - run: docker build -t python2 python2
    - run: docker tag python2 kieluniphysik/python2
    - run: docker push kieluniphysik/python2
  build-python3:
    <<: *defaults
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: echo y | docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - run: docker build -t python3 python3
    - run: docker tag python3 kieluniphysik/python3
    - run: docker push kieluniphysik/python3
  build-python3:
    <<: *defaults
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: echo y | docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - run: docker build -t hugo hugo
    - run: docker tag hugo kieluniphysik/hugo
    - run: docker push kieluniphysik/hugo
workflows:
  version: 2
  build_all:
    jobs:
      - build-texlive
      - build-python2
      - build-python3
      - build-hugo
